version: '3'

services:
  db:
    container_name: db_asm40
    image: mysql:8.0
    ports:
    - 3307:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'asm40'
      MYSQL_DATABASE: asm40
      MYSQL_USER: asm40
      MYSQL_PASSWORD: asm40
    volumes:
      - ./data:/var/lib/mysql
